my_table/urls.py
from django.urls import path,include
from my_table import views

app_name = "my_table"

urlpatterns = [
    path(''                             , views.index               , name = 'index'),
    # path('', include(router.urls)),
    path('<int:Travel_Plan_id>'         , views.detail              , name = 'detail'),
    path('create_tour/<int:plan_id>'    , views.create_tour         , name = 'create_tour'),
    path('create_tour/create_my_table'              , views.create_my_table     , name = 'create_my_table'),
    path('create_plan'                  , views.create_plan         , name = "create_plan"),
    path('create_tour/province_in_area'             , views.province_in_area    , name = 'province_in_area'),
    path("create_tour/tour_in_province"             , views.tour_in_province    , name = "tour_in_province"),
    path('save_plan'                    , views.save_plan           , name = "save_plan"),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('api-auth/', include('rest_framework.urls')),
]

tour_table/urls.py
from django.contrib import admin
from django.urls import include,path
from rest_framework import routers
from my_table import views

router = routers.DefaultRouter()
router.register(r'plan', views.PlanViewSet)

urlpatterns = [
    path('my_table/' , include('my_table.urls')),
    path('', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]

my_table/models.py
from django.db import models

# Create your models here.
class Area(models.Model):
    id      = models.AutoField(primary_key=True)
    name    = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Province(models.Model):
    id      = models.AutoField(primary_key=True)
    area_id = models.ForeignKey(Area                ,on_delete = models.CASCADE)
    name    = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Tourist_Attraction(models.Model):
    id      = models.AutoField(primary_key=True)
    prov_id = models.ForeignKey(Province            ,on_delete = models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Travel_Plan(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    owner = models.ForeignKey('auth.User', related_name='plans', on_delete=models.CASCADE)
    def __str__(self):
        return str(self.name)
        
class My_Table(models.Model):
    id      = models.AutoField(primary_key=True)
    plan_id = models.ForeignKey(Travel_Plan         , on_delete=models.CASCADE)
    tour_id = models.ForeignKey(Tourist_Attraction  , on_delete=models.CASCADE)
    date    = models.DateTimeField(auto_now=False   , auto_now_add=False)
    note    = models.CharField(max_length=200)
    def __str__(self):
        return str(self.id)

my_table/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.urls import reverse
from .models import Area,Province,Tourist_Attraction,My_Table,Travel_Plan
from django.utils import timezone
from rest_framework import viewsets , permissions , generics
from my_table.serializers import PlanSerializer , UserSerializer
from django.contrib.auth.models import User
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from .permissions import IsOwner
# from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters


class PlanViewSet(viewsets.ModelViewSet):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (permissions.IsAuthenticated,IsOwner)
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Travel_Plan.objects.all()
    serializer_class = PlanSerializer
    search_fields = ('name')
    filter_backends = (filters.SearchFilter,)
    # filter_backends = (DjangoFilterBackend,)

    # def get_queryset(self):
    #     if self.request.method == "GET" and self.request.GET:
    #     plan = self.request.user

class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Create your views here.
def index(request):
    travel_plan = Travel_Plan.objects.all()
    return render(request,'my_table/index.html',{'travel_plan':travel_plan})

def detail(request,Travel_Plan_id):
    my_table = My_Table.objects.filter(plan_id = Travel_Plan.objects.get(id = Travel_Plan_id))
    return render(request , 'my_table/detail.html',{'my_table':my_table , 'plan_id':Travel_Plan_id})

def create_plan(request):
    return render(request,"my_table/create_plan.html")

def create_tour(request,plan_id):
    get_area = Area.objects.all()
    get_prov = Province.objects.all()
    get_tour = Tourist_Attraction.objects.all()
    context = {'area':get_area,
               'plan_id':plan_id}
    return render(request,'my_table/create_tour.html',context)

def province_in_area(request):
    prov = Province.objects.filter(area_id=Area.objects.get(id=request.POST['area_id_ref']))
    prov_list = []
    for element in prov:
        prov_list.append({\
            "prov_id":element.id,\
            "prov_name":element.name\
        })
    return JsonResponse(prov_list, safe=False)

def tour_in_province(request):
    tour = Tourist_Attraction.objects.filter(prov_id = Province.objects.get(id=request.POST['prov_id_ref']))
    tour_list = []
    for element in tour:
        tour_list.append({\
            "tour_id":element.id,\
            "tour_name":element.name\
        })
    return JsonResponse(tour_list, safe=False)

def create_my_table(request):
    plan = Travel_Plan.objects.get(id = request.POST['plan_id'])
    test_id = Tourist_Attraction.objects.get(pk=str(request.POST['tour']))
    date_new = request.POST['tour_date']
    note = request.POST['note']
    my_table = My_Table(plan_id = plan , tour_id=test_id,date=date_new,note=note)
    my_table.save()
    return HttpResponseRedirect(reverse('my_table:detail', args=(my_table.id,)))

def save_plan(request):
    plan = Travel_Plan(name = request.POST['plan_name'])
    plan.save()
    return HttpResponseRedirect(reverse('my_table:detail', args=(plan.id,)))

my_table/templates/my_table/create_plan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <big>สร้าง Plan กันเถอะ</big>
    <form action="{% url 'my_table:save_plan'%}" method="post">
        {% csrf_token %}
        <label for="plan_name">ชื่อแผน:</label>
        <input type="text" id="plan_name" name="plan_name" placeholder="ไปเที่ยวกันนนน">
        <input type="submit" value="เพิ่ม plan" />
    </form>

    <form action="{% url 'my_table:index' %}">
        <input type="submit" value="ย้อนกลับ">
    </form>

</body>

</html>

my_table/templates/my_table/create_tour.html
<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>


<body>

    <div class="form-group">
        <label for="area">ภาค:</label>
        <select class="form-control" id="area">
            {% for area_name in area %}
            <option value="{{area_name.id}}">{{area_name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="province">จังหวัด:</label>
        <select class="form-control" id="province">
        </select>
        <form action="{% url 'my_table:create_my_table'%}" method="post">
            {% csrf_token %}
            <label for="tour">สถานที่ท่องเที่ยว:</label>
            <select class="form-control" id="tour" name="tour">
            </select>

            <label for="note">หมายเหตุ:</label>
            <input type="text" id="note" name="note">

            <label for="tour_date">วันที่ไปเที่ยว</label>
            <input type="datetime-local" id="tour_date" name="tour_date">
            <input type="text" id="plan_id" name="plan_id" value={{ plan_id }} hidden>
            <input type="submit" value="เพิ่มรายการ" />
        </form>

        <form action="{% url 'my_table:detail' plan_id %}">
            <input type="submit" value="ย้อนกลับ" />
        </form>
</body>

</html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script>
    function goBack() {
        window.history.back();
    }
</script>
<script>
    $(document).ready(function () {
        // Select area to filter Province
        $("#area").change(function () {
            $("#province").empty()
            var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
            $.post("province_in_area", {
                area_id_ref: $("#area").val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            }, function (data) {
                data.forEach(element => {
                    console.log(element)
                    $("#province").append($("<option></option>")
                        .attr("value", element.prov_id)
                        .text(element.prov_name));
                });
            })
        });

        // Select Province to filter Tour
        $("#province").change(function () {
            $("#tour").empty()
            var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
            $.post("tour_in_province", {
                prov_id_ref: $("#province").val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            }, function (data) {
                data.forEach(element => {
                    console.log(element)
                    $("#tour").append($("<option></option>")
                        .attr("value", element.tour_id)
                        .text(element.tour_name));
                });
            })
        });
    });
</script>

my_table/templates/my_table/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">สถานที่ท่องเที่ยว</th>
                <th scope="col">วัน/เดือน/ปี</th>
                <th scope="col">เวลา</th>
                <th scope="col">รายละเอียด</th>
            </tr>
        </thead>
        <tbody>
            {% for my_table_tmp in my_table %}
            <tr>
                <th center>{{my_table_tmp.id}}</th>
                <td center>{{my_table_tmp.tour_id.name}}</td>
                <td center>{{my_table_tmp.date}}</td>
                <td center>{{my_table_tmp}}</td>
                <td center>{{my_table_tmp.note}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="{% url 'my_table:create_tour' plan_id %}">
        <input type="submit" value="สร้างรายการ" />
    </form>

    <form action="{% url 'my_table:index'%}">
        <input type="submit" value="ย้อนกลับ" />
    </form>

</body>

</html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    function goBack() {
        window.history.back();
    }
</script>

my_table/templates/my_table/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">ชื่อแผน</th>
                <th scope="col">รายการเที่ยว</th>
            </tr>
        </thead>
        <tbody>
            {% for plan in travel_plan %}
            <tr>
                <th center><a href="{% url 'my_table:detail' plan.id %}"</a>{{plan.id}}</th>
                <td center>{{plan.name}}</td>
                <td center>{{plan.my_table_set.count}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="{% url 'my_table:create_plan'%}">
        <input type="submit" value="สร้าง plan เที่ยว" />
    </form>
</body>

</html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>